config/routes.rb
Rails.application.routes.draw do

  resources :comments
  root 'welcome#index'
  get 'signup' => 'users#new'
  get    'login' => 'sessions#new'
  post   'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'new_arrival' => 'ideas#detail'

  resources :users, only: [:index, :show] do
    member do
      get :like_ideas
    end
  end

  resources :ideas do
    member do
      get :liking_users
    end
  end

  post 'like/:idea_id' => 'likes#like', as: 'like'
  delete 'unlike/:idea_id' => 'likes#unlike', as: 'unlike'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :ideas
  resources :relationships, only: [:create, :destroy]
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  has_many :comments

  mount_uploader :catch, CatchUploader

  validates :user_id, presence: true
  validates :idea_name, presence: true
  # validates :content, presence: true, length: {minimum: 20, maximum: 300}

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :logged_in_user, only: [:create, :new, :edit]
  before_action :correct_user, only: [:update, :edit]
  before_action :set_idea, except: [:new, :create, :detail]
  def new
    @idea = Idea.new
  end

  def show
    @user = @idea.user
    @users = @idea.liking_users.order("updated_at DESC").limit(6)
    @comments = @idea.comments.all
    @comment = @idea.comments.build
  end

  def create
    @idea = current_user.ideas.build(idea_params)
    if @idea.save
      flash[:success] = "投稿完了"
      redirect_to root_url
    else
      # @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc)
      render 'ideas/new'
    end
  end

  def edit
  end

  def update
    if @idea.update_attributes(idea_params)
      flash[:success] = "更新完了"
      redirect_to @idea
    else
      render 'edit'
    end
  end

  def detail
    @ideas = Idea.all.order("updated_at DESC").limit(50)
  end

  def liking_users
    @users = @idea.liking_users.order("updated_at DESC")
  end

  private
  def idea_params
    params.require(:idea).permit(:idea_name, :content, :purpose, :remark, :catch)
  end
  def set_idea
    @idea = Idea.find(params[:id])
  end

  def correct_user
    @idea = Idea.find(params[:id])
    @user = User.find(@idea.user.id)
    if !current_user?(@user)
      flash[:notice] = 'アクセスが許可されていません！'
      redirect_to root_path
    end
  end

end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_contents.html.erb
<h5>【アイデア名】</h5>
<p class="indent">
  <%= idea.idea_name %>
</p>
<h5>【概要】</h5>
<p class="indent">
  <%= idea.content %>
</p>
<h5>【目的】</h5>
<p class="indent">
  <%= idea.purpose %>
</p>
<% if idea.remark.nil? %>
    <h5>【備考】</h5>
    <p class="indent">
      なし
    </p>
<% else %>
    <h5>【備考】</h5>
    <p class="indent">
      <%= idea.remark %>
    </p>
<% end %>
<span class="right-side">
  投稿は<%= time_ago_in_words(idea.created_at) %>前 by <%= link_to idea.user.name, @user %>
</span>

app/views/ideas/_form_ideas.html.erb
<%= form_for(idea, html:{ multipart: true}) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label :idea_name, "アイデア名" %>
      <%= f.text_field :idea_name, class: "form-control", placeholder: "例：○○企画" %>
    </div>
    <div class="field">
      <%= f.label :content, "内容" %>
      <%= f.text_area :content, class: "form-control", placeholder: "例：本企画は，○○にメリットが有ります．" %>
    </div>
    <div class="field">
      <%= f.label :purpose, "目的" %>
      <%= f.text_area :purpose, class: "form-control", placeholder: "例：このプロジェクトによって○○という問題を解決出来る！"  %>
    </div>
    <div class="field">
      <%= f.label :remark, "備考(任意)" %>
      <%= f.text_area :remark, class: "form-control", placeholder: "例：開発環境は”Rails 5.0.0.1を使います．" %>
    </div>

    <%= f.submit "完了", class: "btn btn-primary" %>

    <div class="picture">
      <% if idea.catch.present? %>
          <%= image_tag idea.catch.url if idea.catch %>
      <% end %>
      <%= f.label :catch, "キャッチアイ画像(任意)" %>
      <%= f.file_field :catch %>

    </div>
<% end %>

app/views/ideas/_idea.html.erb
<div class="box">
  <h2 class="box-title">アイデア投稿</h2>
  <div class="box-inner">
    <%= form_for(@idea, html:{ multipart: true}) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :idea_name, "アイデア名" %>
          <%= f.text_field :idea_name, class: "form-control", placeholder: "例：○○企画" %>
        </div>
        <div class="field content-box">
          <%= f.label :content, "内容" %>
          <%= f.text_area :content, class: "form-control", placeholder: "例：本企画は，○○にメリットが有ります．" , :size=>"60x10" %>
        </div>
        <div class="field">
          <%= f.label :purpose, "目的" %>
          <%= f.text_area :purpose, class: "form-control", placeholder: "例：このプロジェクトによって○○という問題を解決出来る！"  %>
        </div>
        <div class="field">
          <%= f.label :remark, "備考(任意)" %>
          <%= f.text_area :remark, class: "form-control", placeholder: "例：開発環境は”Rails 5.0.0.1を使います．" %>
        </div>

        <%= f.submit "投稿", class: "btn btn-primary" %>

        <div class="picture">
          <%= f.label :picture, "キャッチアイ画像(任意)" %>
          <%= f.file_field :picture %>
        </div>
    <% end %>
  </div>
</div>

app/views/ideas/_ideas.html.erb
<div class="container-inner inner-default clearfix">
  <% if ideas.present? %>
      <% ideas.each do |idea| %>
          <div class="idea-box">
            <div class="image">
              <div class="img-wrap">
                <% if idea.catch.present? %>
                    <%# 画像が存在したら %>
                    <%= image_tag idea.catch, alt: idea.user.name %>
                <% else %>
                    <%# 画像が存在しなかったら  %>
                    <%= image_tag "no-image.png" %>
                <% end %>
              </div>
            </div>
            <div class="detail">
              <p class="title">
                <%= link_to "アイデア名： " + idea.idea_name, idea_path(idea.id) %>
              </p>
              <p>
                <%= link_to "投稿者名： " + idea.user.name, idea.user %>
              </p>
            </div>
          </div>
      <% end %>
  <% end %>
</div>

app/views/ideas/_show_like.html.erb
<% users.each do |user| %>
    <%= link_to gravatar_for(user, size: 30), user %>
<% end %>

app/views/ideas/detail.html.erb
<%= render 'ideas/ideas', ideas: @ideas %>

app/views/ideas/edit.html.erb
<div class="box">
  <h2 class="box-title">アイデア編集</h2>
  <div class="box-inner">
    <%= render 'ideas/form_ideas', idea: @idea %>
  </div>
</div>

app/views/ideas/liking_users.html.erb
<h2>Likeしてるユーザー一覧</h2>
<ul class="user-list">
  <%= render @users %>
</ul>

app/views/ideas/new.html.erb
<%# render 'ideas/idea', idea: @idea %>

<div class="box">
  <h2 class="box-title">アイデア投稿</h2>
  <div class="box-inner">
    <%= form_for(@idea, html:{ multipart: true}) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :idea_name, "アイデア名" %>
          <%= f.text_field :idea_name, class: "form-control", placeholder: "例：○○企画" %>
        </div>
        <div class="field">
          <%= f.label :content, "内容" %>
          <%= f.text_area :content, class: "form-control", placeholder: "例：本企画は，○○にメリットが有ります．" %>
        </div>
        <div class="field">
          <%= f.label :purpose, "目的" %>
          <%= f.text_area :purpose, class: "form-control", placeholder: "例：このプロジェクトによって○○という問題を解決出来る！"  %>
        </div>
        <div class="field">
          <%= f.label :remark, "備考(任意)" %>
          <%= f.text_area :remark, class: "form-control", placeholder: "例：開発環境は”Rails 5.0.0.1を使います．" %>
        </div>

        <%= f.submit "投稿", class: "btn btn-primary" %>

        <div class="picture">
          <%= f.label :picture, "キャッチアイ画像(任意)" %>
          <%= f.file_field :picture %>
        </div>
    <% end %>
  </div>
</div>

app/views/ideas/show.html.erb
<div class="container-inner inner-sm clearfix">
  <div class="idea-single-main">
    <div class="image">
      <div class="img-wrap">
        <%# TODO アイデアイメージ %>
        <% if @idea.catch.present? %>
            <%= image_tag @idea.catch.url, alt: @idea.idea_name %>
        <% else %>
            <%= image_tag("no-image.png", alt: @idea.idea_name) %>
        <% end %>
      </div>
    </div>
    <div class="title">
      <%= @idea.idea_name %>
    </div>
  </div>

  <div class="idea-single-side">
    <div class="side-box">
      <h4 class="side-box-title">Likeしたユーザー数：<%= link_to @idea.likes.count, liking_users_idea_path(@idea.id), id: "like-count" %>人</h4>
      <div id="like-users" class="side-box-body">
        <% # Likeしたユーザー一覧 %>
          <%= render 'ideas/show_like', users: @users %>
        <%# end %>
      </div>
    </div>
    <div class="text-center">
      <% if logged_in? %>
          <div id="link-like">
            <%= render 'likes/link_like', idea: @idea %>
          </div>
      <% else %>
          <%= link_to 'Like', login_path, class: "btn like btn-danger" %>
      <% end %>
    </div>
    <div class="side-box">
      <h4 class="side-box-title">アイデア内容</h4>
      <div class="side-box-body">
        <%= render 'ideas/contents', idea: @idea %>
      </div>
      <% if current_user == @user %>
          <div>
            <%= link_to "編集", edit_idea_path(@idea.id), class: "btn btn-warning" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

<div>
  <div class="row">
    <div class="col-md-8">
      <%= render 'comments/form', comment: @comment%>
    </div>
    <div class="col-md-4">
      <%= render 'comments/comment', comment: @comment, user: @user, id: "comments" %>
    </div>
  </div>
</div>