config/routes.rb
Rails.application.routes.draw do

  resources :comments
  root 'welcome#index'
  get 'signup' => 'users#new'
  get    'login' => 'sessions#new'
  post   'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'new_arrival' => 'ideas#detail'

  resources :users, only: [:index, :show] do
    member do
      get :like_ideas
    end
  end

  resources :ideas do
    member do
      get :liking_users
    end
  end

  post 'like/:idea_id' => 'likes#like', as: 'like'
  delete 'unlike/:idea_id' => 'likes#unlike', as: 'unlike'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :ideas
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord

  mount_uploader :avatar, AvatarUploader

  has_many :ideas
  has_many :likes, dependent: :destroy
  has_many :like_ideas, through: :likes, source: :idea

  has_many :following_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following_users, through: :following_relationships, source: :followed

  has_many :followed_relationships, class_name:  "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followed_users, through: :followed_relationships, source: :follower

  before_save {self.email = email.downcase}
  validates :name, presence: true, length: {maximum: 50}, uniqueness: {case_sensitive: true}
  VALID_EMAIL_REGEX = /\A[a-zA-Z0-9_\#!$%&`'*+\-{|}~^\/=?\.]+@[a-z0-9][a-z0-9\.-]+\z/i
  validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX},
          uniqueness: {case_sensitive: false}
  has_secure_password

  # フォローする
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end

  # フォロー取り消し
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end

  # followしているかどうか
  def following?(other_user)
    following_users.include?(other_user)
  end

  def feed_items
    Idea.where(user_id: following_user_ids + [self.id])
  end

  def set_image(file)
    if !file.nil?
      file_name = file.original_filename
      File.open("public/user_images/#{file_name}", 'wb') { |f| f.write(file.read) }
      self.avatar = file_name
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update]
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    # file = params[:user][:avatar]
    # @user.set_image(file)
    if @user.save
      log_in @user
      redirect_to @user, notice: "会員登録完了です！"
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @ideas = @user.ideas.order("updated_at DESC")
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      # file = params[:user][:avatar]
      # @user.set_image(file)
      flash[:success] = "更新されました！"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def like_ideas
    @title = "お気に入りした投稿"
    @user = User.find(params[:id])
    @ideas = @user.like_ideas
    render 'show_ideas'
  end

  def following
    @title = "フォロー中のユーザ"
    @user = User.find(params[:id])
    @users = @user.following_users
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user = User.find(params[:id])
    @users = @user.followed_users
    render 'show_follow'
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def correct_user
    @user = User.find(params[:id])
    if !current_user?(@user)
      redirect_to root_path, alert: 'アクセスが許可されていません！'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    unless user.avatar.url
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      size = options[:size]
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mm"
      image_tag(gravatar_url, alt: user.name, class: "gravatar")
    else
      image_tag(user.avatar.url, alt: user.name, class: "gravatar")
    end
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "フォロー", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
    <div id="follow_form">
      <% if current_user.following?(@user) %>
          <%= render 'unfollow' %>
      <% else %>
          <%= render 'follow' %>
      <% end %>
    </div>
<% end %>

app/views/users/_profile.html.erb
<div class="user-profile">
  <div class="icon">
    <%= gravatar_for user, size: 100 %>
  </div>
  <div class="name">
    <h1><%= user.name %></h1>
  </div>
  <div class="status">
    <ul>
      <li>
        <div class="status-label">フォロー</div>
        <div class="status-value">
          <strong>
            <%= link_to user.following_users.count, following_user_path(@user) %>
          </strong>
        </div>
      </li>
      <li>
        <div class="status-label">フォロワー</div>
        <div class="status-value">
          <strong id="followers">
            <%= link_to user.followed_users.count, followers_user_path(@user) %>
          </strong>
        </div>
      </li>
      <li>
        <div class="status-label">お気に入り</div>
        <div class="status-value">
          <strong>
            <%= link_to user.like_ideas.count, like_ideas_user_path(@user) %>
          </strong>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
    <%= f.submit "フォロー解除", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for(user) %>
  <%= link_to user.name, user %> |
  <%= user.email %>
</li>

app/views/users/edit.html.erb
<div class="box">
  <h2 class="box-title">設定</h2>
  <div class="box-inner">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.text_field :name, class: "form-control", placeholder: "お名前" %>
        </div>
        <div class="form-group">
          <%= f.text_field :email, class: "form-control", placeholder: "メールアドレス" %>
        </div>
        <div class="form-group">
          <%= f.password_field :password, class: "form-control", placeholder: "パスワード" %>
        </div>
        <div class="form-group">
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "パスワード（確認）" %>
        </div>
        <div class="form-group">
          <%= image_tag @user.avatar.url, :class => "edit_img" if @user.avatar.url  %>
          <%= f.file_field :avatar %>
        </div>
        <div class="submit-group">
          <%= f.submit "更新する", class: "btn btn-success" %>
        </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="box">
  <h2 class="box-title">会員登録</h2>
  <div class="box-inner">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.text_field :name, class: "form-control", placeholder: "お名前" %>
        </div>
        <div class="form-group">
          <%= f.text_field :email, class: "form-control", placeholder: "メールアドレス" %>
        </div>
        <div class="form-group">
          <%= f.password_field :password, class: "form-control", placeholder: "パスワード" %>
        </div>
        <div class="form-group">
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "パスワード（確認）" %>
        </div>
        <div class="form-group">
          <%= f.label :avatar, "プロフィール画像" %>
          <%= f.file_field :avatar %>
        </div>
        <div class="submit-group">
          <%= f.submit "登録する", class: "btn btn-success" %>
        </div>
    <% end %>
    既に登録している方はこちら！<%= link_to "ログイン画面へ", login_path %>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'profile', user: @user %>
<%= render 'follow_form' if logged_in? %>
<h2>投稿一覧</h2>
<%= render 'ideas/ideas', ideas: @ideas %>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>アイデア投稿数</b>(<%= @user.ideas.count %>)</span>
    </section>
    <section class="stats">
      <% if @users.any? %>
          <div class="user_avatars">
            <% @users.each do |user| %>
                <%= link_to gravatar_for(user, size: 30), user %>
            <% end %>
          </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
        <ul class="users follow">
          <%= render @users %>
        </ul>
    <% end %>
  </div>
</div>

app/views/users/show_ideas.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "プロフィール", @user %></span>
      <span><b>アイデア投稿数</b>(<%= @user.ideas.count %>)</span>
    </section>
    <section class="stats">
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @ideas.any? %>
        <ul class="users follow">
          <%= render 'ideas/ideas', ideas: @ideas %>
        </ul>
    <% end %>
  </div>
</div>