config/routes.rb
Rails.application.routes.draw do

  resources :comments
  root 'welcome#index'
  get 'signup' => 'users#new'
  get    'login' => 'sessions#new'
  post   'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'new_arrival' => 'ideas#detail'

  resources :users, only: [:index, :show] do
    member do
      get :like_ideas
    end
  end

  resources :ideas do
    member do
      get :liking_users
    end
  end

  post 'like/:idea_id' => 'likes#like', as: 'like'
  delete 'unlike/:idea_id' => 'likes#unlike', as: 'unlike'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :ideas
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-inner">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#content" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <h1 class="logo">
            <%# link_to "IdeaVotes", root_path, class: "navbar-brand" %>
            <%= link_to "IdeaVotes", root_path, class: "btn btn-warning" %>
          </h1>
        </div>
        <div class="collapse navbar-collapse" id="content">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "全体", new_arrival_path %></li>
            <% unless logged_in? %>
                <li><%= link_to "新規登録", signup_path %></li>
            <% else %>
                <li>
                  <%= link_to new_idea_path do %>
                    <span class="glyphicon glyphicon-plus" aria-hidden="true">
                      アイデアを投稿する
                    </span>
                  <% end %>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <%= gravatar_for current_user, size: 20 %>
                    <%= current_user.name %>
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to "プロフィール", current_user %>
                    </li>
                    <li>
                      <%= link_to "設定", edit_user_path(current_user.id) %>
                    </li>
                    <li role="separator" class="divider"></li>
                    <li>
                      <%= link_to "ログアウト", logout_path, method: :delete %>
                    </li>
                  </ul>
                </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaVotes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= analytics_init if Rails.env.production? %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  </body>
</html>